Improve init script

diff --git a/sshd.init b/sshd.init
--- a/sshd.init
+++ b/sshd.init
@@ -142,13 +142,28 @@ start()
 
 stop()
 {
+
 	echo -n $"Stopping $prog: "
-	if [ -n "`pidfileofproc $SSHD`" ] ; then
-	    killproc $SSHD
-	else
-	    failure $"Stopping $prog"
+	if [ ! -f "$PIDFILE" ]; then
+		# not running; per LSB standards this is "ok"
+		action $"Stopping $prog: " /bin/true
+		return 0
 	fi
-	RETVAL=$?
+	PID=`cat "$PIDFILE"`
+	if [ -n "$PID" ]; then
+		/bin/kill "$PID" >/dev/null 2>&1
+		RETVAL=$?
+		if [ $RETVAL -eq 0 ]; then
+			RETVAL=1
+			action $"Stopping $prog: " /bin/false
+		else
+			action $"Stopping $prog: " /bin/true
+		fi
+	else
+		 # failed to read pidfile
+		action $"Stopping $prog: " /bin/false
+		RETVAL=4
+	fi
 	# if we are in halt or reboot runlevel kill all running sessions
 	# so the TCP connections are closed cleanly
 	if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
@@ -157,7 +172,8 @@ stop()
 	    trap TERM
 	fi
 	[ $RETVAL -eq 0 ] && rm -f $lockfile
-	echo
+	rm -f "$PIDFILE"
+        return $RETVAL
 }
 
 reload()
